# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Application

on:
  workflow_dispatch:

env:
  telegram_token: ${{ secrets.TELEGRAM_TOKEN }}
  telegram_username: ${{ secrets.TELEGRAM_USERNAME }}
  geminiapi_key: ${{ secrets.GEMINIAPI_KEY }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Python script
      run: python app.py
